name: "Deploy to Netlify"
description: "A custom JavaScript action to deploy a React site to Netlify."
inputs:
  auth_token:
    description: "Netlify authentication token"
    required: true
  site_name:
    description: This is used for site name
    required: true
  token: 
    description: This is used for github authentication
    required: true


runs:
  using: "node16"
  main: "main.js"
