name: "Deploy to Netlify"
description: "A custom JavaScript action to deploy a React site to Netlify."
inputs:
  auth_token:
    description: "Netlify authentication token"
    required: true
  build_directory:
    description: "The directory containing the build files"
    required: true


runs:
  using: "node16"
  main: "main.js"
