name: Simple workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build artifacts
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Deploy to Netlify
        uses: ./.github/actions/deploy-to-netlify
        with:
          auth_token: ${{secrets.NETLIFY_TOKEN}}
          site_name: dancing-pastelito-9838b7
